### ISSUE TITLE
Switch to enums instead of int literals for constants

### ISSUE THREAD

**Issue by szabopeter** [pygamelib/pygamelib#219]
**Is your feature request related to a problem? Please describe.**
No immediate problem, this change would allow for better type hinting:
instead of ```def next_move(self) -> int:``` you would have ```def next_move(self) -> Direction:```
This is more accurate as next_move() is never supposed to return -1 or anything else than the 9 constants specified in the constants module.

**Describe the solution you'd like**
Instead of 
```
# Directions
NO_DIR = 10000000
UP = 10000001
```
you would have
```
class Direction(enum.IntEnum):
  NO_DIR = 10000000
  UP = 10000001
```

**Describe alternatives you've considered**
It can also be an option to keep the current constants and define the enums additionally to preserve compatibility but also allow for a more type-safe usage style - but you would still have breaking changes if an existing method (e.g. next_move() mentioned above) starts returning a different type than before... You could also mark the existing methods deprecated and introduce alternate versions - no idea how many of these exist...

**Additional context**
- In some places (e.g. serialization), conversion to/from int will be necessary e.g. ```my_direction.value``` or ```Direction(my_serialized_direction)```
- ```Direction.UP == 10000001``` is true by default when using enum.IntEnum
- All in all, I consider the widespread use of ints for all kinds of data an architectural/technical debt that is difficult to change at this point (best done at a major version change) but will likely just get more difficult later on

**Comment by arnauddupuis** [comment]
I've been wanting to change all of these for `dataclass` for a long time! So I wholeheartedly agree! To be honest, the int thing is laziness on my side as at first the only constants existing were the directions (back in the days when I was just maintaining that for my kids' coding classes). It got out of hand...

If I remember correctly the `@dataclass` decorator was introduced in 3.9. If that's the case, we could consider deprecating support for Python versions lesser than 3.9. It needs to be discussed, I don't know how much 3.8 there still is out in real life.

This is most certainly a breaking change, but as you said: it will always be breaking.

The actuators' `next_move()` method can return either a direction or a `pygamelib.base.Vector2D`. I think that this change is beneficial for all the reasons you cited and that there is no way to change that without a painful breaking change. So let's do it once and for all.

**Comment by szabopeter** [comment]
dataclasses require python 3.7 and enums are available since 3.4

**Comment by arnauddupuis** [comment]
Oh... my bad... 
Well then let's do it. It also means that `pygamelib.gfx.ui.UiConfig` and `pygamelib.gfx.particles.EmitterProperties` need to be converted to dataclass. I'll create the issues.

**Comment by arnauddupuis** [comment]
I have started to implement this in this PR: #221

All new constants are now enums. I propose that following this, we actually create all of the constants as enums while keeping the old constants alive for 1.4, mark them as deprecated, and remove them in 1.5 or 1.6.
